name: Fullstack CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # FRONTEND
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Lint frontend
      working-directory: ./frontend
      run: npm run lint

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # BACKEND
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Check backend syntax
      working-directory: ./backend
      run: node -e "require('./src/server.js')"
